-- 코드를 입력하세요
# 게시글 제목, 게시글 ID, 댓글 ID, 댓 작성 ID, 댓 내용, 댓 작성일
# 댓 작성일 기준 오름차순, 게시글 제목 기준 오름차순 정렬
SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE,'%Y-%m-%d') AS DATE_FORMAT
FROM USED_GOODS_BOARD A 
JOIN USED_GOODS_REPLY B ON A.BOARD_ID = B.BOARD_ID
WHERE A.CREATED_DATE >= '2022-10-01' AND A.CREATED_DATE < '2022-11-01'
ORDER BY B.CREATED_DATE ASC, A.TITLE ASC;